// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcctxkjwohqillciengv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjY3R4a2p3b2hxaWxsY2llbmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjc2MDIsImV4cCI6MjA2OTY0MzYwMn0.wM5_wMIvztqqwBmnCd0K8QVpWQ0G7n94LKJ8xkKgQAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});